<?php

declare(strict_types=1);

namespace App\Modules\Blueprint\DTOs;

/**
 * Configuration for Scripts tab.
 *
 * @param  ScriptEntry[]  $scripts
 */
final class ScriptsConfig
{
    /**
     * @param  ScriptEntry[]  $scripts
     */
    public function __construct(
        public readonly array $scripts = [],
    ) {}

    public static function fromArray(array $data): self
    {
        $rawScripts = $data['scripts'] ?? [];

        if (!is_array($rawScripts)) {
            return new self([]);
        }

        return new self(
            scripts: array_map(
                fn (array $script) => ScriptEntry::fromArray($script),
                $rawScripts,
            ),
        );
    }

    public function toArray(): array
    {
        return [
            'scripts' => array_map(
                fn (ScriptEntry $script) => $script->toArray(),
                $this->scripts,
            ),
        ];
    }

    /**
     * Generate a shell script string from the entries.
     */
    public function toShellScript(): string
    {
        if (empty($this->scripts)) {
            return '';
        }

        $lines = ['#!/bin/bash', '# Auto-generated by CoVaR', ''];

        foreach ($this->scripts as $script) {
            if ($script->description !== '') {
                $lines[] = "# {$script->description}";
            }
            $lines[] = $script->command;
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * Return structured output for TabOutput content.
     *
     * @return array{scripts: array, shell_script: string}
     */
    public function toOutputArray(): array
    {
        return [
            'scripts' => $this->toArray()['scripts'],
            'shell_script' => $this->toShellScript(),
        ];
    }

    public function hasScripts(): bool
    {
        return count($this->scripts) > 0;
    }
}
